### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by jason-fox** [smartfog/adapter#1]
This repo has been identified as missing  a `LICENSE` and therefore needs to be updated

Elements without a `LICENSE` are technically _All rights reserved_ and should not be used in Open Source

- MUST requirement from the TSC

Could you add one please.

**Comment by smartfog** [comment]
Hi Jason, 

We consider to move this repository into the FogFlow repository as a sub-folder. In this case, we do not need a new license for a separated repository. 

How do you think?

**Comment by jason-fox** [comment]
If this repo can be considered as a separate component with a separate lifecycle, a simpler approach in my opinion would be to add a copy of the BSD-Clause 4 [License](https://github.com/smartfog/fogflow/blob/master/LICENSE) into this repository. This would mean that anyone pulling this repo would know that they definitely have permission. 

It is your codebase, and technically (until you add a `LICENSE`) no-one else can use this at the moment - _they have the right to download only_.

**Comment by smartfog** [comment]
I added the same BSD-Clause 4 License into this repository.  Thanks!
